root_path: '/lustre/fs1/home/sr463454/CLT/plantwild'


load_cache: False
load_pre_feat: False

#load_cache: True
#load_pre_feat: True


# ------ Basic Config ------
dataset: 'plantwild'
shots: 0
backbone: 'RN101'

lr: 0.001
augment_epoch: 5
train_epoch: 30